In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [32]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [33]:
## Preprocess the data and removing unwanted colunms
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [34]:
### Encode categorical variables
Label_encoder_gender= LabelEncoder()
data['Gender']= Label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [35]:
## Onehot Encode 'Geography

onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [36]:
### Combine All the colunms with the orginal data
data = pd.concat([data.drop('Geography', axis=1, errors='ignore'), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [37]:
## Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [38]:
## split the data in training and testing
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [39]:
## scale these features
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [40]:
## Save the encoder and scaler for later use

with open('Label_encoder_gender.pk1', 'wb') as file:
    pickle.dump(Label_encoder_gender, file) 

with open('onehot_encoder_geo.pk1', 'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression Problem Statement

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [42]:
model=Sequential([
    Dense(64,activation='relu', input_shape=(X_train.shape[1],)), ## This is My first hidden layer
    Dense(32,activation='relu'), # this is my secound Hidden Layer
    Dense(1)## Output layer

])


## compile the model
model.compile(optimizer= 'adam', loss = 'mean_absolute_error', metrics=['mae'] )

model.summary()

e:\ANN-Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
import datetime

In [50]:
### set up the Tensoreboard
from tensorflow.keras.callbacks import EarlyStopping ,TensorBoard

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [51]:
### Set up Early Stopping

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [53]:
### Train the model
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]  
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 100363.8203 - mae: 100363.8203 - val_loss: 98470.1094 - val_mae: 98470.1094
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99486.0859 - mae: 99486.0859 - val_loss: 96724.6094 - val_mae: 96724.6094
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 96472.8125 - mae: 96472.8125 - val_loss: 92341.9219 - val_mae: 92341.9219
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90629.5312 - mae: 90629.5312 - val_loss: 85165.6484 - val_mae: 85165.6484
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 82261.8438 - mae: 82261.8438 - val_loss: 76167.0547 - val_mae: 76167.0547
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 72761.3828 - mae: 72761.3828 - val_loss: 67086.1953 - val_mae: 67086.1953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 63998.5117 - mae: 63998.5117 - val_loss: 59602.8867 - val_mae: 59602.8867
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 57408.9102 - mae: 57408.9102 - val_loss: 54571.9141 - val_mae: 54571.9141
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53418.8672 - mae: 53418.8672 - val_loss: 52009.4336 - val_mae: 52009.4336
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51513.5352 - mae: 51513.5352 - val_loss: 51081.1484 - val_mae: 51081.1484
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50777.7344 - mae: 50777.7344 - val_loss: 50835.3281 - val_mae: 50835.3281
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50505.5234 - mae: 50505.5234 - val_loss: 50747.6367 - val_mae: 50747.6367
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50379.2188 - mae: 50379.2188 - val_loss: 50689.9883 - val_mae: 50689.9883
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50297.9727 - mae: 50297.9727 - val_loss: 50650.4570 - val_mae: 50650.4570
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50236.4492 - mae: 50236.4492 - val_loss: 50617.8828 - val_mae: 50617.8828
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50183.1406 - mae: 50183.1406 - val_loss: 50585.5625 - val_mae: 50585.5625
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50134.5312 - mae: 50134.5312 - val_loss: 50552.9727 - val_mae: 50552.9727
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50096.9531 - mae: 50096.9531 - val_loss: 50516.6797 - val_mae: 50516.6797
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50059.9961 - mae: 50059.9961 - val_loss: 50496.0430 - val_mae: 50496.0430
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50024.8086 - mae: 50024.8086 - val_loss: 50468.5391 - val_mae: 50468.5391
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49994.5898 - mae: 49994.5898 - val_loss: 50450.8242 - val_mae: 50450.8242
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49966.8672 - mae: 49966.8672 - val_loss: 50427.4961 - val_mae: 50427.4961
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49939.9102 - mae: 49939.9102 - val_loss: 50414.6055 - val_mae: 50414.6055
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49914.2656 - mae: 49914.2656 - val_loss: 50395.2266 - val_mae: 50395.2266
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49888.8438 - mae: 49888.8438 - val_loss: 50376.4570 - val_mae: 50376.4570
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49865.4570 - mae: 49865.4570 - val_loss: 50370.0547 - val_mae: 50370.0547
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49845.5234 - mae: 49845.5234 - val_loss: 50357.7031 - val_mae: 50357.7031
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49821.3477 - mae: 49821.3477 - val_loss: 50344.6992 - val_mae: 50344.6992
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49803.3242 - mae: 49803.3242 - val_loss: 50337.3828 - val_mae: 50337.3828
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49785.9336 - mae: 49785.9336 - val_loss: 50336.1992 - val_mae: 50336.1992
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49765.0273 - mae: 49765.0273 - val_loss: 50331.2344 - val_mae: 50331.2344
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49752.8281 - mae: 49752.8281 - val_loss: 50329.7109 - val_mae: 50329.7109
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49733.8828 - mae: 49733.8828 - val_loss: 50320.1406 - val_mae: 50320.1406
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49719.0000 - mae: 49719.0000 - val_loss: 50312.1953 - val_mae: 50312.1953
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49703.2188 - mae: 49703.2188 - val_loss: 50321.2852 - val_mae: 50321.2852
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49688.4297 - mae: 49688.4297 - val_loss: 50306.5469 - val_mae: 50306.5469
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49671.9414 - mae: 49671.9414 - val_loss: 50308.6406 - val_mae: 50308.6406
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49661.7344 - mae: 49661.7344 - val_loss: 50293.7188 - val_mae: 50293.7188
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49646.8164 - mae: 49646.8164 - val_loss: 50296.1445 - val_mae: 50296.1445
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49636.1797 - mae: 49636.1797 - val_loss: 50285.7305 - val_mae: 50285.7305
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49624.8633 - mae: 49624.8633 - val_loss: 50295.0156 - val_mae: 50295.0156
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49613.5039 - mae: 49613.5039 - val_loss: 50304.9805 - val_mae: 50304.9805
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49601.1367 - mae: 49601.1367 - val_loss: 50298.6641 - val_mae: 50298.6641
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49592.8516 - mae: 49592.8516 - val_loss: 50306.7383 - val_mae: 50306.7383
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49583.9219 - mae: 49583.9219 - val_loss: 50286.3789 - val_mae: 50286.3789
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.1914 - mae: 49571.1914 - val_loss: 50299.6914 - val_mae: 50299.6914
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49559.8164 - mae: 49559.8164 - val_loss: 50295.5039 - val_mae: 50295.5039
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49551.1211 - mae: 49551.1211 - val_loss: 50289.6094 - val_mae: 50289.6094
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49543.4102 - mae: 49543.4102 - val_loss: 50294.1094 - val_mae: 50294.1094
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49534.4805 - mae: 49534.4805 - val_loss: 50306.3945 - val_mae: 50306.3945

In [57]:
###
%reload_ext tensorboard

In [60]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 24500), started 0:00:23 ago. (Use '!kill 24500' to kill it.)

In [61]:
### Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50285.7305 - mae: 50285.7305
Test MAE: 50285.73046875

In [62]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.